import './fonts.css'

export const fontList = 
    [
        'Abhaya Libre',
        'AlexBrush',
        'Aller',
        'Arial',
        'Barlow',
        'Brush Script MT',
        'Caviar Dreams',
        'Cooper Hewitt',
        'Courier New',
        'D-Din',
        'DejaVu',
        'Fira Sans',
        'Georgia',
        'Gill Sans',
        'Glacial Indifference',
        'Helvetica',
        'Impact',
        'Josefin Sans',
        'Lucida Console',
        'Montserrat',
        'Muli',
        'Norwester',
        'Oswald',
        'Playfair',
        'Poppins',
        'Quicksand',
        'Raleway',
        'Rubik',
        'Sansation',
        'SourceCode Pro',
        'Tahoma',
        'Times New Roman',
        'Trebuchet MS',
        'Verdana'
    ];